/** This file stores various elements which can be useful when running QA or debug tasks. */

/** All Color Tokens (Array)
An array containing all the LkColor tokens. */

export const LkColorsArray: LkColor[] = [
  "primary",
  "onprimary",
  "primarycontainer",
  "onprimarycontainer",
  "secondary",
  "onsecondary",
  "secondarycontainer",
  "onsecondarycontainer",
  "tertiary",
  "ontertiary",
  "tertiarycontainer",
  "ontertiarycontainer",
  "error",
  "onerror",
  "errorcontainer",
  "onerrorcontainer",
  "background",
  "onbackground",
  "surface",
  "onsurface",
  "surfacevariant",
  "onsurfacevariant",
  "shadow",
  "inversesurface",
  "scrim",
  "inverseonsurface",
  "inverseprimary",
  "success",
  "onsuccess",
  "successcontainer",
  "onsuccesscontainer",
  "warning",
  "onwarning",
  "warningcontainer",
  "onwarningcontainer",
  "info",
  "oninfo",
  "infocontainer",
  "oninfocontainer",
  "primaryfixed",
  "onprimaryfixed",
  "primaryfixeddim",
  "onprimaryfixedvariant",
  "secondaryfixed",
  "onsecondaryfixed",
  "secondaryfixeddim",
  "onsecondaryfixedvariant",
  "tertiaryfixed",
  "ontertiaryfixed",
  "tertiaryfixeddim",
  "ontertiaryfixedvariant",
  "surfacedim",
  "surfacebright",
  "surfacecontainerlowest",
  "surfacecontainerlow",
  "surfacecontainer",
  "surfacecontainerhigh",
  "surfacecontainerhighest",
  "outline",
  "outlinevariant",
];

/** LK Colors with On-Tokens */
