on:
  push:
    branches:
    - main
    - release/*

jobs:
  create_issues:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: dtinth/todo-actions@v0.2.0
